### ISSUE TITLE
Waystones Not Dropping When Mined

### ISSUE THREAD

**Issue by cecaelion** [sylvxa/sswaystones#12]
**Minecraft Version:** 1.21
**Fabric Version:** 0.16.7
**sswaystones Version:** 1.1.3-HOTFIX

Hello! This is an excellent mod and players on my server use it extensively for its utility. It's helped foster a sense of community on the server, especially as we don't use /tpa commands, but also because players are willing to travel to register the waystone for others' builds.

However, we have recently run into a problem: placed Waystones are not dropping themselves when mined. This happens with pickaxes of every level, with and without the Silk Touch enchantment. I attempted to re-add the loot_table/blocks/waystone.json file via a datapack, but they're still refusing to drop themselves. It's not the end of the world, as they're fairly easy to craft and the other mods and I don't mind handing out "insurance claims" to folks who need them, but it is inconvenient. 

This might be user error, but we aren't certain. I can provide more details if necessary (i.e. full server modlist). Thanks!

**Comment by sylvxa** [comment]
Hi there! I have confirmed this issue and I'm working on a fix.

**Comment by sylvxa** [comment]
Fixed in [1.1.4-HOTFIX](https://modrinth.com/mod/sswaystones/version/xM2GcoJ0)
