### ISSUE TITLE
Waystones are fragile af

### ISSUE THREAD

**Issue by Merith-TK** [sylvxa/sswaystones#2]
I one hit punch in survival and they break

**Comment by sylvxa** [comment]
This will be fixed in the next version of the mod, will close when published.

**Comment by Merith-TK** [comment]
alrigth!

**Comment by sylvxa** [comment]
Fixed in version [1.1.0](https://modrinth.com/mod/sswaystones/version/1.1.0) (or commit [93f1d70](https://github.com/sylvxa/sswaystones/commit/93f1d706ead9bd4133eecc79638384685134c49e))
