### ISSUE TITLE
Use blocks under the waystone as an optional display in chest gui

### ISSUE THREAD

**Issue by noiverre** [sylvxa/sswaystones#3]
One player are having too many waystones, they said it's kinda hard to find the correct waystone to teleport to, although it's alphabetically sorted, the user must hover over a few of heads to find the correct waystone name

![image](https://github.com/user-attachments/assets/acde2b1a-90d9-49e5-8c21-37f8f0218738)
This idea is more of a qol enhancement, by adding a button switch in the boxed slot, it then can detect what block are placed under the waystone, and if the block is solid, it will return the block as the icon instead of player heads, if non-solid blocks are detected then it will fall back into player head

By having this, player at least can modify blocks under waystones to indicate a specific teleport, for example an Enderman farm waystone can have an End Stone as the icon, while a Storage waystone can have a Barrel as the icon

**Comment by sylvxa** [comment]
This is a great suggestion! Though, I may just implement an icon menu rather than using the block underneath. This is on my task list and i'll work on it when I have the time.

**Comment by sylvxa** [comment]
Hey! This is implemented for the most part in [0456b26](https://github.com/sylvxa/sswaystones/commit/0456b262bf4451e73aa81b969e0e7b58ac7ce40f), needs more testing and documentation but should be good! If you are eager, you can compile from source.

**Comment by noiverre** [comment]
Hey, I just have the chance to test it now, from simple test using three blocks, apparently everything works fine
![image](https://github.com/user-attachments/assets/1b6edb5a-03e1-4aea-acdd-ffae01c04516)
![image](https://github.com/user-attachments/assets/66faf599-0ef0-490c-a991-ef0dd9c98c13)
![image](https://github.com/user-attachments/assets/c2683744-3517-48d7-bca1-c3bf1370fd17)
![image](https://github.com/user-attachments/assets/6baac78a-67cb-4c77-81e0-93def344a2df)
![image](https://github.com/user-attachments/assets/41701017-9e26-4ba7-b18d-d61d7f9a4e27)

It works across dimension too (overworld and nether), didn't test with end or unloaded chunks but should be fine

**Comment by sylvxa** [comment]
Good catch! The player head issue should be fixed in [3957432](https://github.com/sylvxa/sswaystones/commit/3957432095cb86c9000a1495a535b7387caf6a9e) (or [1.1.1](https://modrinth.com/mod/sswaystones/version/1.1.1)).
