### ISSUE TITLE
Creative block replacer deleted my waystone block

### ISSUE THREAD

**Issue by MarkHarrisMedia** [sylvxa/sswaystones#7]
I accidentally replaced the waystone with a dirt block and now its gone, I cant edit it.

I didn't realize I had this mod activated https://modrinth.com/mod/creative-block-replacer

The teleportation still works but now I cant move the waystone or edit it, and the pearl is not spinning anymore.

![image](https://github.com/user-attachments/assets/97fb1cc0-2676-4455-99ec-d1c302c625f4)

**Comment by MarkHarrisMedia** [comment]
is there any commands I can use to delete the waystone manually since the block is gone?

or maybe a way to reload the block / waystone?

I tried reloading config command but that didn't work.

**Comment by sylvxa** [comment]
I'll work on adding a command as I assumed this issue would pop up, for now try placing another waystone in its place and restart the server, that might fix it.

**Comment by xllifi** [comment]
Same with Axiom's feature "Tinker"

**Comment by MarkHarrisMedia** [comment]
> I'll work on adding a command as I assumed this issue would pop up, for now try placing another waystone in its place and restart the server, that might fix it.

tried placing walls and waystones, didnt work

**Comment by sylvxa** [comment]
Sorry for the wait, I have a fix implemented and I hope to get a build out tomorrow.

**Comment by sylvxa** [comment]
Issue fixed in [f6a5b57](https://github.com/sylvxa/sswaystones/commit/f6a5b57687f68e05c1d6dd70b80dcdfb5eb4bd14), available in [Release 1.1.3](https://modrinth.com/mod/sswaystones/version/1Ekywgvg)

**Comment by MarkHarrisMedia** [comment]
Yay, thank you so much @sylvxa
