### ISSUE TITLE
Teleporting between dimensions on bedrock does not work

### ISSUE THREAD

**Issue by MarkHarrisMedia** [sylvxa/sswaystones#8]
When someone teleports to a different world (i.e. overworld to end, it puts them at 32k blocks above the ground..)

It wont fix itself until logging out and back in. This problem only happens for bedrock players. It's really unfortunate because most of our players use bedrock.

I was able to replicate the same error in a brand new server, it did the same thing.
You are welcome to join my two servers to test it out for yourself if you would like. I can't figure out how to fix it, please help!

Also, I should take note that both of my servers have this mod active: Amplified Nether
"The nether explorer's simple dream: doubled height and amplified terrain." (Amplified_Nether_1.21_v1.2.5.jar)

Alpha MC - Cross-Play Survival with Server-Side Waystones 1.1.3
Java / PC: Connection Address: 172.240.47.153:25584
Bedrock: Connection Address: 172.240.47.153:25543

![image](https://github.com/user-attachments/assets/866446f1-7df2-4aa5-9331-8ff55812b2da)

**Comment by sylvxa** [comment]
Hi there! There isn't anything in this code that should be causing this. My guess is that Amplified Nether is at fault? If not, try changing Geyser's `above-bedrock-nether-building` to `true`.

**Comment by MarkHarrisMedia** [comment]
> Hi there! There isn't anything in this code that should be causing this. My guess is that Amplified Nether is at fault? If not, try changing Geyser's `above-bedrock-nether-building` to `true`.

I tried this, and it did not fix the issue.

I have been trying other things, including raising the build limit of the nether. But still, when a bedrock players uses any waystone to go to a different dimension, it still puts them at 32k blocks above the ground and requires the player to restart their client for it to fix itself.

**Comment by sylvxa** [comment]
I don't really know what could be causing this; maybe a Geyser issue? We use vanilla code to handle teleporting and there aren't any extra changes between Bedrock and Java. If it's fixed via re-log there might be a hack I can implement, can't promise a said date for when I'll figure it out though. If someone else wants to look into it feel free to make a PR.

**Comment by MarkHarrisMedia** [comment]
![IMG_2301](https://github.com/user-attachments/assets/11dea7bd-c1fa-43a4-a546-df97e4685795)

**Comment by MarkHarrisMedia** [comment]
I removed these mods and it fixed the problem, however a new problem presents itself.

Removed
1: c2me-fabric-mc1.21-0.2.0+alpha.11.109.jar
2: HigherNether-1.0.2.jar

Now I get a repeating / consistent error message flooding my server console.. It looks like this:
![image](https://github.com/user-attachments/assets/263e37c3-80f4-4a13-b5b4-131c51284bf1)

**Comment by sylvxa** [comment]
Hi! As much as I would like to help, the errors you are describing are *not related* to sswaystones, not to mention that the original issue is also not related to this mod. I'm closing this issue as I would prefer that support like this be kept in its appropriate channels. (ex. [HigherNether's report page](https://github.com/DeeChael/HigherNether/issues) or [C2ME's](https://github.com/RelativityMC/C2ME-fabric/issues))

**Comment by MarkHarrisMedia** [comment]
> Hi! As much as I would like to help, the errors you are describing are _not related_ to sswaystones, not to mention that the original issue is also not related to this mod. I'm closing this issue as I would prefer that support like this be kept in its appropriate channels. (ex. [HigherNether's report page](https://github.com/DeeChael/HigherNether/issues) or [C2ME's](https://github.com/RelativityMC/C2ME-fabric/issues))

Fair enough, I have posted my new bug in both of those githubs. Thank you!

**Comment by MichaelBTryin** [comment]
@MarkHarrisMedia - I am trying to locate your C2ME issue - as I have that mod too, and am having the same issue.
I'll keep looking, but any assistance would be much apreciated.
